### ISSUE TITLE
[App Request] <spotifydl>

### ISSUE THREAD

**Issue by NikoAnd** [WisdomSky/CasaOS-Coolstore#11]
### Brief Description:

(kinda like the youtube downloader but for Spotify)

### Project URL:

(https://github.com/SathyaBhat/spotify-dl)

### Additional Information:

()

### Screenshots:

(Optional: Any sample screenshots of the UI)

**Comment by WisdomSky** [comment]
Added a spotify downloader app.

![image](https://github.com/WisdomSky/CasaOS-Coolstore/assets/6792172/d2388370-6c0d-4ab7-a746-fdc42d494004)
