### ISSUE TITLE
[Not Working] Immich

### ISSUE THREAD

**Issue by jtenniswood** [WisdomSky/CasaOS-Coolstore#13]
## Description

When launched the link shows '500 getaddrinfo EAI_AGAIN immich-server'

## Expected Behavior

For the link to launch the default immich admin page.

**Comment by jtenniswood** [comment]
Not sure if it's connected to this change...
https://github.com/immich-app/immich/discussions/2025
'Please update your docker-compose.yml file to include the new container and .env file to have the new environment variable, which is TYPESENSE_API_KEY=some-random-text.'

**Comment by WisdomSky** [comment]
Hi @jtenniswood,

That issue is much likely the issue. what I can recommend is to copy the docker-compose file of the immich app from this repo manually and specify the TYPESENSE_API_KEY in it.

And after that, you can start the app using this command:

    casaos-cli app-management install -f /path/to/docker-compose.yml

**Comment by jtenniswood** [comment]
Thanks for the tip, it ended up being a bit more involved that just add the API key, but I managed to get a working compose file. There were a couple of issues with the original...
- missing hostnames for redis and the database
- missing API keys in the environment settings for microservices and immich.

I've set the API key as 'casaos', not the most secure, but it will all be local anyway, and people can change them later, at least this creates a working foundation.

If you agree, could you update the compose file in the store for others to use?
Many thanks

`
name: immich
services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:v1.72.2
    command:
      - start.sh
      - immich
    volumes:
      - /DATA/AppData/immich/upload:/usr/src/app/upload
    environment:
      - TYPESENSE_API_KEY=casaos
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=casaos
      - DB_PASSWORD=casaos
      - DB_DATABASE_NAME=casaos
      - DB_PORT=5432
      - REDIS_HOSTNAME=immich_redis
      - IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
    depends_on:
      - redis
      - database
      - typesense
      - immich-machine-learning
    restart: always
  immich-microservices:
    image: ghcr.io/immich-app/immich-server:v1.72.2
    command:
      - start.sh
      - microservices
    volumes:
      - /DATA/AppData/immich/upload:/usr/src/app/upload
    environment:
      - TYPESENSE_API_KEY=RN23GFr1s6jQ9kgSNg2O7fYcAUXU7127
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=casaos
      - DB_PASSWORD=casaos
      - DB_DATABASE_NAME=casaos
      - DB_PORT=5432
      - REDIS_HOSTNAME=immich_redis
    depends_on:
      - redis
      - database
      - typesense
    restart: always
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.72.2
    volumes:
      - /DATA/AppData/immich/model/cache:/cache
    environment:
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=casaos
      - DB_PASSWORD=casaos
      - DB_DATABASE_NAME=casaos
      - DB_PORT=5432
      - REDIS_HOSTNAME=immich_redis
    restart: always
  immich-web:
    image: ghcr.io/immich-app/immich-web:v1.72.2
    restart: always
  typesense:
    image: typesense/typesense:0.24.1
    environment:
      - TYPESENSE_API_KEY=casaos
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - /DATA/AppData/immich/typesense/data:/data
    restart: always
  redis:
    image: redis:6.2-alpine
    restart: always
    hostname: immich_redis
  database:
    image: postgres:15.3
    hostname: immich_postgres
    environment:
      POSTGRES_PASSWORD: casaos
      POSTGRES_USER: casaos
      POSTGRES_DB: casaos
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /DATA/AppData/immich/postgresql/data:/var/lib/postgresql/data
    restart: always
  immich-proxy:
    image: ghcr.io/immich-app/immich-proxy:v1.72.2
    environment:
      - IMMICH_SERVER_URL=http://immich-server:3001
      - IMMICH_WEB_URL=http://immich-web:3000
      - IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
    ports:
      - '2283:8080'
    depends_on:
      - immich-server
      - immich-web
      - immich-machine-learning
    restart: always
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: immich-proxy
  description:
    en_us: Self-hosted photos and videos backup tool
  tagline:
    en_us: Self-hosted photos and videos backup tool
  developer: Immich
  author: WisdomSky
  icon: https://immich.app/img/logo.png
  thumbnail: https://immich.app/img/logo.png
  title:
    en_us: Immich
  category: Coolstore
  port_map: '2283'
`

**Comment by WisdomSky** [comment]
Sure, thanks for forwarding your working docker-compose.yaml file.

**Comment by WisdomSky** [comment]
updated immich.

Also now includes an instruction for specifying the TYPESENSE_API_KEY

![image](https://github.com/WisdomSky/CasaOS-Coolstore/assets/6792172/47df3631-aa04-4b7b-b79b-0013277f242e)
