### ISSUE TITLE
[App Request] Stirling PDF

### ISSUE THREAD

**Issue by ldwrs** [WisdomSky/CasaOS-Coolstore#14]
### Brief Description:

This is a powerful locally hosted web based PDF manipulation tool using docker that allows you to perform various operations on PDF files, such as splitting merging, converting, reorganizing, adding images, rotating, compressing, and more. 

### Project URL:
https://hub.docker.com/r/frooodle/s-pdf
https://github.com/Frooodle/Stirling-PDF

**Comment by WisdomSky** [comment]
Added.

Re-register your CasaOS Coolstore appstore by removing and re-adding it in CasaOS to immediately update your listing.

![image](https://github.com/WisdomSky/CasaOS-Coolstore/assets/6792172/460437eb-cdef-4b31-82ad-1cbe3847f24c)
