### ISSUE TITLE
[App Request] <file converter>

### ISSUE THREAD

**Issue by NikoAnd** [WisdomSky/CasaOS-Coolstore#16]
### Brief Description:

(a local hosted file type converter comparable to cloud convert. supports music formats , document formats, ect.)

### Project URL:

(https://github.com/dwaaan/HRConvert2-Docker/blob/master/README.md)

### Additional Information:

(Any helpful information that you want to add and to let the one who will work on adding this app know about things that need to be considered)

### Screenshots:

(Optional: Any sample screenshots of the UI)

**Comment by WisdomSky** [comment]
Added.

![image](https://github.com/WisdomSky/CasaOS-Coolstore/assets/6792172/fe33351c-8fd2-4a19-94cb-adc818a9b7c0)

![image](https://github.com/WisdomSky/CasaOS-Coolstore/assets/6792172/f002c7c4-e522-4dbf-bf7e-9d307544a129)
