### ISSUE TITLE
[App Request] <retro arch web player>

### ISSUE THREAD

**Issue by NikoAnd** [WisdomSky/CasaOS-Coolstore#18]
### Brief Description:

(retro game emulator that you can play the games on the web interface) 

### Project URL:

(https://hub.docker.com/r/inglebard/retroarch-web)

### Additional Information:

(Any helpful information that you want to add and to let the one who will work on adding this app know about things that need to be considered)

### Screenshots:

(Optional: Any sample screenshots of the UI)

**Comment by WisdomSky** [comment]
@NikoAnd done.

![image](https://github.com/WisdomSky/CasaOS-Coolstore/assets/6792172/2785bd85-00d1-429f-b460-aa74deb7ea4a)
