### ISSUE TITLE
[App Request] Redis

### ISSUE THREAD

**Issue by georgeslegros** [WisdomSky/CasaOS-Coolstore#19]
### Brief Description:

Redis is an open source (BSD licensed), in-memory data structure store, used as a database, cache, and message broker

### Project URL:

https://redis.io/

### Additional Information:

Well, that'd be great to have Redis built in the store

### Screenshots:

(Optional: Any sample screenshots of the UI)

**Comment by WisdomSky** [comment]
Done.

![image](https://github.com/WisdomSky/CasaOS-Coolstore/assets/6792172/f43faf1d-092a-4cfc-a7ba-0b44ff67867b)

**Comment by georgeslegros** [comment]
Oh mate, that was fast, you rock!! Thanks a lot!
