### ISSUE TITLE
[Not Working] Wireguard Server

### ISSUE THREAD

**Issue by xp1ode** [WisdomSky/CasaOS-Coolstore#2]
## Description
Wireguard fails to install with "Container wg-easy-app-1 exited(1)" error.

## Expected Behavior

The icon shows up on the front page as if it's installed but when i open the settings, everything is blank.

**Comment by WisdomSky** [comment]
Issue resolved. please try again.

If you are facing the same issue, unregister the appstore and then register it again to reflect the new changes.

**Comment by xp1ode** [comment]
Thanks, the container installs but the settings page still displays blank. Would i be able to make changes in the wg0.conf file in the appdata folder?

[settings](https://github.com/xp1ode/new/blob/main/wg-easy.png)

**Comment by WisdomSky** [comment]
> Thanks, the container installs but the settings page still displays blank. Would i be able to make changes in the wg0.conf file in the appdata folder?
> 
> 
> 
> [settings](https://github.com/xp1ode/new/blob/main/wg-easy.png)

I'm bot sure what causes your wg-easy settings to not appear but you might want to report that to casaos instead. that's like a casaos-related issue.

**Comment by thor9898** [comment]
I don't know what happens with wg-easy and casa os, but the container from this store doesn't work for me, nor does it work if I try to custom install it with the docker compose, but installing the docker container straight to my computer worked straight away
