### ISSUE TITLE
[App Request] ESPHome

### ISSUE THREAD

**Issue by thor9898** [WisdomSky/CasaOS-Coolstore#22]
### Brief Description:

Managing ESPHome device

### Project URL:
https://github.com/esphome/esphome
https://esphome.io
https://hub.docker.com/r/esphome/esphome

### Screenshots:

![image](https://github.com/WisdomSky/CasaOS-Coolstore/assets/58491644/9ca233bc-e078-4e5e-a112-cdebf7fba7b3)

I attatch the .yaml file of the container I'm actually running on my casaos
[ESPHome.zip](https://github.com/WisdomSky/CasaOS-Coolstore/files/12588840/ESPHome.zip)

**Comment by kd9lsv** [comment]
Sent in the main Appstore.
- https://github.com/IceWhaleTech/CasaOS-AppStore/pull/292

**Comment by WisdomSky** [comment]
Hi @kd9lsv,

Added.
