### ISSUE TITLE
[App Request] Matter

### ISSUE THREAD

**Issue by thor9898** [WisdomSky/CasaOS-Coolstore#23]
### Brief Description:

Matter container for Home Assistant

### Project URL:

https://github.com/home-assistant-libs/python-matter-server

### Additional Information:
I attatch the .yaml file of the container I'm actually running on my casaos
[Matter.zip](https://github.com/WisdomSky/CasaOS-Coolstore/files/12588915/Matter.zip)

**Comment by WisdomSky** [comment]
Hi @thor9898 ,

Added.
