### ISSUE TITLE
[App Request] Docker Mail Server

### ISSUE THREAD

**Issue by thor9898** [WisdomSky/CasaOS-Coolstore#24]
### Brief Description:

Simple containerized mail server

### Project URL:

https://github.com/docker-mailserver/docker-mailserver
https://hub.docker.com/r/mailserver/docker-mailserver/

**Comment by WisdomSky** [comment]
Hi @thor9898 ,

Adding the said mail server is not possible at the moment due to the limitations of CasaOS.
