### ISSUE TITLE
[App Request] <App Name Here>

### ISSUE THREAD

**Issue by AndreaDiNapoli** [WisdomSky/CasaOS-Coolstore#25]
### Brief Description:

Immich updated

### Project URL:

https://github.com/imagegenius/docker-immich

### Additional Information:

Can you please update immich to latest version? keeping it out of date give some problem with the app, thank you!

### Screenshots:

(Optional: Any sample screenshots of the UI)

**Comment by WisdomSky** [comment]
Hi @AndreaDiNapoli ,

Immich support has been moved to this other 3rd-party appstore:

https://github.com/bigbeartechworld/big-bear-casaos
