### ISSUE TITLE
[App Request] TwoFactor

### ISSUE THREAD

**Issue by OfflinePing** [WisdomSky/CasaOS-Coolstore#26]
### Brief Description:

This is a Webdashboard that Allows Multiple Users to Host & Manage their 2FA Tokens & Codes.

### Project URL:

[(TwoFactor Github)](https://github.com/OfflinePing/TwoFactor)

### Additional Information:

If you need it in Docker Form I am always happy to help <3

### Screenshots:

https://user-images.githubusercontent.com/54213976/253800017-f151372f-e7f9-4040-94d1-cb8ef96494c0.gif

**Comment by WisdomSky** [comment]
Hi @OfflinePing,

There is an existing similar app in the Official CasaOS appstore.

![image](https://github.com/WisdomSky/CasaOS-Coolstore/assets/6792172/1914d00a-6afe-4abc-8391-f0b000fba7bb)

You might want to check that one out instead.
