### ISSUE TITLE
[Not Working] Immich

### ISSUE THREAD

**Issue by floco** [WisdomSky/CasaOS-Coolstore#28]
## Description

database container fail to start after an upgrade, found this in the log:
"The data directory was initialized by PostgreSQL version 15, which is not compatible with this version 16.0"

## Expected Behavior
had to rollback the postgres image to 15.4.
In theory should even stick 14 as this is what official immich docker-compose.yml use: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441

This is how I downgraded:
update /var/lib/casaos/apps/immich/docker-compose.yml like this "image: postgres:15.4"
docker compose down --rmi all
docker compose up -d

**Comment by WisdomSky** [comment]
Hi @floco,

We've decided that an another maintainer will host immich.

Please check out this appstore instead for Immich:

https://github.com/bigbeartechworld/big-bear-casaos
