### ISSUE TITLE
[App Request] ovpn-admin

### ISSUE THREAD

**Issue by mertonv** [WisdomSky/CasaOS-Coolstore#29]
### Brief Description:

Simple web UI to manage OpenVPN users, their certificates & routes in Linux.

### Project URL:
https://github.com/flant/ovpn-admin

### Additional Information:

There is a ready-to-use [docker-compose.yaml](https://github.com/flant/ovpn-admin/blob/master/docker-compose.yaml), so you can just change/add values you need and start it with [start.sh](https://github.com/flant/ovpn-admin/blob/master/start.sh).

Not mine but should be of interest to CasaOS

### Screenshots:
https://raw.githubusercontent.com/flant/ovpn-admin/master/img/ovpn-admin-users.png
https://raw.githubusercontent.com/flant/ovpn-admin/master/img/ovpn-admin-metrics.png

**Comment by WisdomSky** [comment]
Hi @mertonv,

Adding ovpn-admin into the list is not possible at the moment due to the limitations of CasaOS.

I apologize for the inconvenience.
