### ISSUE TITLE
[Not Working] Traefik

### ISSUE THREAD

**Issue by x0r2d2** [WisdomSky/CasaOS-Coolstore#30]
## Description

Traefik after installation don't start. After checking application folder, I found that config files were created as folders. How can this be fixed? 

![Screenshot](https://i.imgur.com/WAqV1kr.png) ![screenshot 2023-09-21 016.png](https://i.imgur.com/rH7YWHT.png)

**Comment by WisdomSky** [comment]
Hi @R2D2me ,

An another appstore has a traefik. you might want to check it out.

https://github.com/mr-manuel/CasaOS-HomeAutomation-AppStore
