### ISSUE TITLE
[Not Working] Reactive Resume

### ISSUE THREAD

**Issue by jtnishi** [WisdomSky/CasaOS-Coolstore#31]
## Description

Two issues:

1. App installs, but does not expose any settings for change/checking.
2. When trying to register a new account, displays an empty error message. Quick console check shows 404 response, but cannot readily check the logs to see if I can troubleshoot.

## Expected Behavior

1. Upon install, app should still show some settings upon using the kebab menu and selecting settings.
2. App should allow registration and login for new users created.

**Comment by WisdomSky** [comment]
Hi @jtnishi,

Thanks for reporting, I'll check on it soon. Thanks

**Comment by WisdomSky** [comment]
Hi @jtnishi,

After troubleshooting the issues with Reactive Resume, I decided to just drop Reactive Resume as it seemed to be hounded with different kind of issues. For example, I managed to fix the issue with the unable to register, but after that a new issue surfaces. I will look into an alternative for reactive resume and add that into the list.

I apologize for the inconvenience.
