### ISSUE TITLE
[Not Working] Caddy incorrect volume bindings

### ISSUE THREAD

**Issue by Jerakin** [WisdomSky/CasaOS-Coolstore#53]
## Description
Caddy host binds are not correct

The bindings are
```
source: /DATA/AppData/$AppID/caddyfile
target: /etc/caddy/caddyfile
```

but caddy requires the caddyfile to be capitalized, this would be correct.
```
source: /DATA/AppData/$AppID/Caddyfile
target: /etc/caddy/Caddyfile
```

Maybe there is issues with the fact isn't an extension is an issue for compose?

I fixed this locally by going into the settings on the container in CasaOS and changing it to
```
source: /DATA/AppData/$AppID/caddyfile/Caddyfile
target: /etc/caddy/Caddyfile
```

**Comment by WisdomSky** [comment]
Fixed.
