### ISSUE TITLE
[App Request] Immich

### ISSUE THREAD

**Issue by techieanant** [WisdomSky/CasaOS-Coolstore#6]
### Brief Description:

immich is a self-hosted photo and video backup solution directly from your mobile phone.

### Project URL:

https://github.com/immich-app/immich

### Additional Information:

This is probably the best self hosted photo and video backup application. 

### Screenshots:

[(Optional: Any sample screenshots of the UI)](https://raw.githubusercontent.com/immich-app/immich/main/design/immich-screenshots.png)

**Comment by WisdomSky** [comment]
Immich has been added however, I can't verify if it's fully working as it requires to provide a `TYPESENSE_API_KEY`.

You can add a `TYPESENSE_API_KEY` by opening the app settings and click the typesense tab. There you'll find a `TYPESENSE_API_KEY` entry in the `environment variables` section.
