### ISSUE TITLE
[Not Working] spotDL

### ISSUE THREAD

**Issue by fabfabretti** [WisdomSky/CasaOS-Coolstore#60]
## Description

When attempting to search a song, the app gives out the error "Network Error". 
![immagine](https://github.com/WisdomSky/CasaOS-Coolstore/assets/59342704/c6d858e5-8a5f-476c-bae4-021671e5a769)
This mention has already been noted on SpotDL's issues page, here: https://github.com/spotDL/spotify-downloader/issues/2035
At the end of the thread, a user has found a fix that I personally found to be working on my CasaOS system. It looks like the app is being pushed to the wrong port, and it's a very easy fix (I'll do a PR right after opening this issue).

## Expected Behavior

The app should be able to look for songs, rather than giving out an error.

**Comment by WisdomSky** [comment]
Fixed.
