### ISSUE TITLE
[App Request] casaos-cloudflared

### ISSUE THREAD

**Issue by fanmingming** [WisdomSky/CasaOS-Coolstore#9]
A new version of cloudflared is available. Visit our [downloads](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation) page to upgrade.

**Comment by WisdomSky** [comment]
@fanmingming Thanks for reminding. I've done updated the docker image and also made a request to the casaos main appstore repository to update the version.

 https://github.com/IceWhaleTech/CasaOS-AppStore/pull/226

**Comment by fanmingming** [comment]
> @fanmingming Thanks for reminding. I've done updating the [WisdomSky/casaos-cloudflared](https://hub.docker.com/r/wisdomsky/casaos-cloudflared/tags) docker image and also made a request to the casaos main appstore repository to update the version.
> 
> [IceWhaleTech/CasaOS-AppStore#226](https://github.com/IceWhaleTech/CasaOS-AppStore/pull/226)

THX.
After restarting the server, the service fails to take effect, and it requires re-entering the web page to delete the token, save, and reinstall the Cloudflared Service for it to work again. How can I make the service continue to work effectively after a Linux system reboot?

**Comment by WisdomSky** [comment]
> THX.
> After restarting the server, the service fails to take effect, and it requires re-entering the web page to delete the token, save, and reinstall the Cloudflared Service for it to work again. How can I make the service continue to work effectively after a Linux system reboot?


Yes. I'm aware of this issue. Thanks. I will fix it this weekend.

**Comment by WisdomSky** [comment]
@fanmingming the issues relating to the tunnel service not starting after restarting the container has been resolved.

https://github.com/WisdomSky/CasaOS-Cloudflared/commit/b658205cd7f35bccc1144ceeea2c0bba38b105c1

**Comment by WisdomSky** [comment]
@fanmingming uninstall the casaos cloudflared from main appstore and install the one from CasaOS Coolstore as it is contains the updated version which contains the fix for the tunnel service not restarting after restarting the server.
 https://github.com/WisdomSky/CasaOS-Coolstore

**Comment by fanmingming** [comment]
.The CasaOS Coolstore has been installed. What is the name of the application? Can you please tell me? Thanks.

**Comment by WisdomSky** [comment]
Still cloudflared, but under coolstore

![image](https://github.com/WisdomSky/CasaOS-Coolstore/assets/6792172/d2749af7-69a6-4d7f-849c-f506edcb819d)

**Comment by fanmingming** [comment]
Thank you, the application has been deployed successfully.
